"""initial schema

Revision ID: 588e57e4e807
Revises: 
Create Date: 2025-10-04 14:36:55.236464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '588e57e4e807'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('people',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('surname', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('courtesy_title', sa.Enum('SR', 'SRA', 'SRTA', name='courtesytitle'), nullable=False),
    sa.Column('boss', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('can_talk', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['email'], ['users.email'], ),
    sa.PrimaryKeyConstraint('name', 'surname', 'email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('people')
    op.drop_table('users')
    # ### end Alembic commands ###
